services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_DB: paketabot
      POSTGRES_USER: paketabot
      POSTGRES_PASSWORD: paketabot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paketabot"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - paketabot-postgres:/var/lib/postgresql/data

volumes:
  paketabot-postgres:

