namespace PaketaBot

open System

type IRepositoryStore =
    abstract Save: Repository -> Async<unit>
    abstract Remove: RepositoryId -> Async<unit>
    abstract TryGet: RepositoryId -> Async<Repository option>
    abstract ListEnabled: unit -> Async<Repository list>
    abstract RecordPublication: RepositoryId * Publication -> Async<unit>
    abstract TryGetPublication: RepositoryId -> Async<Publication option>
    abstract TryAcceptDelivery: deliveryId: string -> Async<bool>
    abstract ReleaseDelivery: deliveryId: string -> Async<unit>

type IGitHubGateway =
    abstract GetDefaultHead: Repository -> Async<string>
    abstract DownloadArchive: Repository * sha: string -> Async<byte array>
    abstract GetPermission: Repository * login: string -> Async<RepositoryPermission>
    abstract Publish: PublishUpdate -> Async<Publication>
    abstract Comment: Repository * pullRequest: int * body: string -> Async<unit>

type IArtifactStore =
    abstract Put: Repository * sha: string * archive: byte array -> Async<string>

type ISandboxRunner =
    abstract Run: RunnerRequest -> Async<RunnerResult>

type IJobQueue =
    abstract Enqueue: UpdateJob -> Async<unit>

type WebhookDeliveryOutcome =
    | ProcessedDelivery
    | DuplicateDelivery

module WebhookDelivery =
    /// Claim and dispatch one webhook delivery, retaining only successful claims.
    ///
    /// decision: releases failed claims so a later GitHub retry can recover transient dispatch failures
    /// invariant: only the claim winner dispatches, and a failed dispatch releases its claim before propagating
    /// tradeoff: handlers remain idempotent because retry can repeat effects completed before a later effect failed
    let handle (store: IRepositoryStore) deliveryId dispatch =
        async {
            let! accepted = store.TryAcceptDelivery deliveryId

            if not accepted then
                return DuplicateDelivery
            else
                try
                    do! dispatch ()
                    return ProcessedDelivery
                with error ->
                    do! store.ReleaseDelivery deliveryId
                    return raise error
        }

module PullRequestBody =
    let render changes =
        let rows =
            changes
            |> List.map (fun change -> $"| `{change.Name}` | `{change.Previous}` | `{change.Current}` |")
            |> String.concat "\n"

        $"""PaketaBot updated the versions allowed by `paket.dependencies`.

| Package | From | To |
|---|---:|---:|
{rows}

Generated by PaketaBot. Repository CI remains responsible for validation.
"""

type UpdateService(store: IRepositoryStore, github: IGitHubGateway, artifacts: IArtifactStore, runner: ISandboxRunner) =
    /// Resolve and publish one idempotent repository update.
    ///
    /// invariant: repository archives cross into the runner without GitHub credentials or installation tokens
    member _.Run(job: UpdateJob) =
        async {
            match! store.TryGet job.RepositoryId with
            | None -> return Skipped "repository is not registered"
            | Some repository when not repository.Enabled -> return Skipped "repository is disabled"
            | Some repository ->
                try
                    let! baseSha = github.GetDefaultHead repository
                    let! archive = github.DownloadArchive(repository, baseSha)
                    let! artifactPath = artifacts.Put(repository, baseSha, archive)

                    let request = {
                        Repository = Repository.fullName repository
                        BaseSha = baseSha
                        ArtifactPath = artifactPath
                        OutputPath = ""
                    }

                    let! result = runner.Run request

                    match result.Status, result.LockFile with
                    | RunnerStatus.NoChange, _ -> return Unchanged
                    | RunnerStatus.Updated, Some lockFile ->
                        let! previousPublication = store.TryGetPublication repository.Id

                        let publish = {
                            Repository = repository
                            BaseSha = baseSha
                            ExpectedHead = previousPublication |> Option.map _.HeadSha
                            Branch = Branches.Weekly
                            Path = "paket.lock"
                            Content = lockFile
                            Title = "chore(deps): update Paket dependencies"
                            Body = PullRequestBody.render result.Changes
                        }

                        let! publication = github.Publish publish
                        do! store.RecordPublication(repository.Id, publication)
                        return Published publication
                    | _ -> return RunFailed result.Messages
                with ex ->
                    return RunFailed [ ex.Message ]
        }

module CommandHandler =
    /// Handle an authorized command written on PaketaBot's currently tracked pull request.
    ///
    /// invariant: comments on untracked pull requests never enqueue work or receive bot responses
    let handle
        (store: IRepositoryStore)
        (github: IGitHubGateway)
        (queue: IJobQueue)
        (repositoryId: RepositoryId)
        (pullRequest: int)
        (login: string)
        (body: string)
        =
        async {
            match Commands.tryParse body with
            | None -> return false
            | Some _ ->
                match! store.TryGet repositoryId with
                | None -> return false
                | Some repository ->
                    match! store.TryGetPublication repositoryId with
                    | Some publication when
                        publication.PullRequestNumber = pullRequest
                        && Branches.isOwned publication.Branch
                        ->
                        let! permission = github.GetPermission(repository, login)

                        if RepositoryPermission.canRequestUpdate permission then
                            do!
                                queue.Enqueue {
                                    RepositoryId = repositoryId
                                    Trigger = RequestedBy login
                                }

                            do! github.Comment(repository, pullRequest, "PaketaBot queued a fresh dependency update.")
                            return true
                        else
                            do!
                                github.Comment(
                                    repository,
                                    pullRequest,
                                    "Only repository maintainers can request PaketaBot updates."
                                )

                            return false
                    | _ -> return false
        }
