namespace PaketaBot

open System

type IGitHubGateway =
    abstract GetRepository: owner: string * name: string -> Async<Repository>
    abstract TryGetPublication: Repository -> Async<Publication option>
    abstract GetBranchHead: repository: Repository * branch: string -> Async<string option>
    abstract CreateCommit: update: PublishUpdate * parentShas: string list -> Async<string>
    abstract CreateBranch: repository: Repository * branch: string * commitSha: string -> Async<unit>
    abstract FastForwardBranch: repository: Repository * branch: string * commitSha: string -> Async<unit>
    abstract CreatePullRequest: update: PublishUpdate -> Async<int>
    abstract UpdatePullRequest: update: PublishUpdate * pullRequestNumber: int -> Async<unit>

type IPaketResolver =
    abstract Resolve: unit -> Async<ResolutionResult>

module PullRequestBody =
    /// Describe the observable lock-file change without inventing package upgrades.
    ///
    /// decision: reports dependency requirements separately because they can change without upgrading resolved packages
    /// invariant: an empty resolved-version diff never claims that package versions were updated
    let render (changes: VersionChange list) (requirementChanges: RequirementChange list) =
        match changes, requirementChanges with
        | [], [] ->
            $"""{PullRequests.Marker}
Paket refreshed `paket.lock` without changing resolved package versions.

No resolved version or dependency-requirement change could be summarized from the lock file.

Generated by PaketaBot. Repository CI remains responsible for validation.
"""
        | [], requirementChanges ->
            let rows =
                requirementChanges
                |> List.map (fun change ->
                    $"| `{change.Name}` | `{change.RequiredBy}` | `{change.Previous}` | `{change.Current}` |")
                |> String.concat "\n"

            $"""{PullRequests.Marker}
Paket refreshed dependency requirements recorded in `paket.lock` without changing resolved package versions.

| Package | Required by | From | To |
|---|---|---:|---:|
{rows}

Generated by PaketaBot. Repository CI remains responsible for validation.
"""
        | changes, requirementChanges ->
            let rows =
                changes
                |> List.map (fun change -> $"| `{change.Name}` | `{change.Previous}` | `{change.Current}` |")
                |> String.concat "\n"

            let requirements =
                match requirementChanges with
                | [] -> ""
                | requirementChanges ->
                    let requirementRows =
                        requirementChanges
                        |> List.map (fun change ->
                            $"| `{change.Name}` | `{change.RequiredBy}` | `{change.Previous}` | `{change.Current}` |")
                        |> String.concat "\n"

                    $"""

Paket also refreshed dependency requirements recorded in `paket.lock`.

| Package | Required by | From | To |
|---|---|---:|---:|
{requirementRows}
"""

            $"""{PullRequests.Marker}
PaketaBot updated the versions allowed by `paket.dependencies`.

| Package | From | To |
|---|---:|---:|
{rows}
{requirements}

Generated by PaketaBot. Repository CI remains responsible for validation.
"""

type ResolveService(resolver: IPaketResolver) =
    /// Resolve one dependency update without publisher credentials.
    ///
    /// invariant: resolver exceptions become typed failures that can cross the Actions artifact boundary
    member _.Run() =
        async {
            try
                return! resolver.Resolve()
            with ex ->
                return {
                    Status = Failed
                    LockFile = None
                    Changes = []
                    RequirementChanges = []
                    Messages = [ ex.Message ]
                }
        }

type PublishService(github: IGitHubGateway) =
    let publication branch pullRequestNumber headSha = {
        Branch = branch
        PullRequestNumber = pullRequestNumber
        HeadSha = headSha
        IsOpen = true
    }

    let createPullRequestAfterBranchMutation update commitSha =
        async {
            try
                let! pullRequestNumber = github.CreatePullRequest update
                return publication update.Branch pullRequestNumber commitSha
            with ex ->
                return
                    raise (
                        Exception(
                            $"GitHub did not confirm a pull request after updating {update.Branch}. "
                            + "Rerun PaketaBot first; if no owned pull request exists, follow PaketaBot's recovery procedure. "
                            + ex.Message,
                            ex
                        )
                    )
        }

    /// Publish one typed dependency resolution from the credential-free job.
    ///
    /// decision: uses the marked pull request as durable publication state because the Action has no database
    /// invariant: only a successful resolution containing paket.lock can reach the GitHub publisher
    /// decision: updates an open pull request before its branch so the ref update is the final fallible GitHub mutation
    /// invariant: refreshing an open owned pull request performs no GitHub API call after moving its branch
    /// tradeoff: creating a pull request still requires a branch first, so uncertain failures need fail-closed human recovery
    member _.Run(repository: Repository, baseSha: string, result: ResolutionResult) =
        async {
            try
                match result.Status, result.LockFile with
                | NoChange, _ -> return Unchanged
                | Updated, Some lockFile ->
                    let! previousPublication = github.TryGetPublication repository
                    let! currentHead = github.GetBranchHead(repository, Branches.Weekly)

                    let publish = {
                        Repository = repository
                        BaseSha = baseSha
                        Branch = Branches.Weekly
                        Path = PaketFiles.Lock
                        Content = lockFile
                        Title = "chore(deps): update Paket dependencies"
                        Body = PullRequestBody.render result.Changes result.RequirementChanges
                    }

                    let expectedHead = previousPublication |> Option.map _.HeadSha

                    let publicationPlan =
                        match Branches.planPublication baseSha expectedHead currentHead with
                        | Ok plan -> plan
                        | Error message -> invalidOp message

                    let parentShas = Branches.commitParents baseSha publicationPlan
                    let! commitSha = github.CreateCommit(publish, parentShas)

                    match publicationPlan, previousPublication with
                    | Branches.FastForwardFrom _, Some previous when previous.IsOpen ->
                        do! github.UpdatePullRequest(publish, previous.PullRequestNumber)
                        do! github.FastForwardBranch(repository, publish.Branch, commitSha)

                        return Published(publication publish.Branch previous.PullRequestNumber commitSha)
                    | Branches.FastForwardFrom _, Some _ ->
                        do! github.FastForwardBranch(repository, publish.Branch, commitSha)
                        let! value = createPullRequestAfterBranchMutation publish commitSha
                        return Published value
                    | Branches.CreateFrom _, _ ->
                        do! github.CreateBranch(repository, publish.Branch, commitSha)
                        let! value = createPullRequestAfterBranchMutation publish commitSha
                        return Published value
                    | Branches.FastForwardFrom _, None ->
                        return invalidOp "a verified branch head requires tracked publication state"
                | _ -> return RunFailed result.Messages
            with ex ->
                return RunFailed [ ex.Message ]
        }
