name: Paket dependencies

on:
  schedule:
    - cron: "17 4 * * 1"
      timezone: "Europe/Oslo"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: paketabot-weekly
  cancel-in-progress: false

jobs:
  update:
    uses: ./.github/workflows/paketabot.yml
    permissions:
      contents: read
    secrets:
      paketabot_token: ${{ secrets.PAKETABOT_TOKEN }}
